### ISSUE TITLE
Failed to activate the pandoc package

### ISSUE THREAD

**Issue by klingel** [jagregory/atom-pandoc-preview#24] opened 2015-07-16 15:41 UTC
[Enter steps to reproduce below:]

1. Toggle Command Palette
1. `Pandoc Preview: Show`

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [pandoc](https://github.com/jagregory/atom-pandoc-preview) package, v0.2.0

### Stack Trace

Failed to activate the pandoc package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/user/.atom/packages/pandoc/lib/pandoc-view.coffee:1:1)
  at /home/user/.atom/packages/pandoc/lib/pandoc-view.coffee:9:3
  at Object.<anonymous> (/home/user/.atom/packages/pandoc/lib/pandoc-view.coffee:102:5)
  at Object.<anonymous> (/home/user/.atom/packages/pandoc/lib/pandoc-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/.atom/packages/pandoc/lib/pandoc.coffee:4:14)
  at Object.<anonymous> (/home/user/.atom/packages/pandoc/lib/pandoc.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:236:14)
  at /usr/share/atom/resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -5:28.6.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -5:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:24.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:23.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:22.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:22.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:20.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:19.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:17.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:17.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:13 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 pandoc-preview:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "live-archive",
      "block-cursor"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true
  },
  "pandoc": {
    "languages": {},
    "args": "-s -S --tab-stop=2 --toc --toc-depth=4 --variable=toctitle:TOC --from markdown link_attributes footnotes raw_html fenced_code_blocks backtick_code_blocks autolink_bare_uris strikeout hard_line_breaks -t html5 --ascii -o /home/user/company/docs/proj/proj.html"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.7
atom-pair, v1.1.6
atom-ternjs, v0.6.8
autoclose-html, v0.18.0
autocomplete-emojis, v2.2.2
change-case, v0.6.0
color-picker, v2.0.10
file-icons, v1.5.8
git-log, v0.4.1
git-plus, v5.2.2
git-projects, v1.15.0
hex, v0.6.2
highlight-line, v0.11.0
jsformat, v0.9.0
language-ejs, v0.2.0
language-kotlin, v0.3.0
language-rust, v0.4.3
linter, v1.2.4
linter-jshint, v1.0.5
linter-less, v2.0.3
linter-rust, v0.2.4
minimap, v4.12.0
pandoc, v0.2.0
racer, v0.15.2
redacted, v0.5.0
script, v2.26.3
script-runner, v1.8.3
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by jagregory** [comment] 2015-07-21 22:25
Duplicate of #22.

**Closed by jagregory** 2015-07-21 22:25 UTC
